#!/bin/bash

mcmc=false
flags=""
args=()
for arg in "$@"; do
  case $arg in
    -h|--he-enhanced)
      flags+=", /final, /heenhanced"
      ;;
    -f|--final)
      flags+=", /final"
      ;;
    -m|--mcmc)
      mcmc=true
      ;;
    *)
      args+=("$arg")
      ;;
  esac
done

if [[ "$mcmc" == "true" ]]; then
   echo "Running in MCMC mode."
  eidl2<<EOF
  abundmc, ni='${args[0]}'
EOF
else
  echo "Running with standard models."
  eidl2<<EOF
  abund, ni='${args[0]}'${flags}
EOF
fi
