#!/bin/bash

heenhanced=false
args=()
for arg in "$@"; do
  case $arg in
    -h|--he-enhanced)
      heenhanced=true
      ;;
    *)
      args+=("$arg")
      ;;
  esac
done

if [[ "$heenhanced" == "true" ]]; then
  echo "Running with He-enhanced models."
  eidl2<<EOF
  synth, ni='${args[0]}', /heenhanced
EOF
else
  echo "Running with standard models."
  eidl2<<EOF
  synth, ni='${args[0]}'
EOF
fi
