#!/bin/bash

flags=""
args=()
for arg in "$@"; do
  case $arg in
    -h|--he-enhanced)
      flags+=", /heenhanced"
      ;;&
    *)
      args+=("$arg")
      ;;
  esac
done

echo "Running with standard models."
eidl2<<EOF
synth, ni='${args[0]}'${flags}
EOF
